name: 'do-release'

on:
  pull_request_target:
    types: [closed]

jobs:

  release_job:
    uses: bedita/github-workflows/.github/workflows/release.yml@v1
    with:
      main_branch: 'main'
      dist_branches: '["main"]'

  update_major_tag:
      runs-on: ubuntu-latest
      needs: release_job
      steps:
        - uses: actions/checkout@v3
        - uses: rickstaa/action-create-tag@v1
          with:
            tag: 'v${{ needs.release_job.outputs.major }}'
            force_push_tag: true
