name: 'release'

on:
  workflow_call:
    inputs:
      main_branch:
        description: Main branch, in format of a string, where a new major release is allowed
        required: true
        type: string
      dist_branches:
        required: true
        description: Branches to execute on, in format of a string JSON array
        type: string
      version_ini_path:
        required: false
        description: Path to version.ini file (optional)
        type: string
      version_ini_prefix:
        required: false
        description: Content version.ini file (optional)
        type: string
    outputs:
      version:
        description: The final release version
        value: ${{ jobs.release-on-push.outputs.version }}
      major:
        description: The release major version number
        value: ${{ jobs.release-on-push.outputs.major }}

jobs:

  debug:
    if: github.event.pull_request.merged
    runs-on: 'ubuntu-latest'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

  release-on-push:
    if: github.event.pull_request.merged
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Retrieve last tag on branch
        run: |
          echo "TAG_NAME=$(git describe --tags --match "v*.*.*" --abbrev=0 | cut -c 2-)" >> $GITHUB_OUTPUT

        id: last_tag

      - name: Debug last tag
        run: |
          echo last tag ${{ steps.last_tag.outputs.TAG_NAME }}
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: '${{ steps.last_tag.outputs.TAG_NAME }}'
          separator: '.'
          maxsplit: 3

      - name: Calculate new versions
        env:
          MAJOR: ${{ steps.split.outputs._0 }}
          MINOR: ${{ steps.split.outputs._1 }}
          PATCH: ${{ steps.split.outputs._2 }}
        run: |
          echo "NEW_MAJOR=$(echo $((MAJOR+1)).0.0)" >> $GITHUB_OUTPUT
          echo "NEW_MINOR=$(echo $MAJOR.$((MINOR+1)).0)" >> $GITHUB_OUTPUT
          echo "NEW_PATCH=$(echo $MAJOR.$MINOR.$((PATCH+1)))" >> $GITHUB_OUTPUT
        id: versions

      - name: New possible releases
        run: |
          echo new major ${{ steps.versions.outputs.NEW_MAJOR }}
          echo new minor ${{ steps.versions.outputs.NEW_MINOR }}
          echo new patch ${{ steps.versions.outputs.NEW_PATCH }}
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: branch

      - name: Debug branch name
        run: |
          echo current branch ${{ steps.branch.outputs.BRANCH }}
      - name: Exit on bad tag
        if: ${{ contains(github.event.pull_request.labels.*.name, 'release:major') && !contains(steps.branch.outputs.BRANCH, inputs.main_branch) }}
        run: |
          echo Can't create a major release on branch ${{ steps.branch.outputs.BRANCH }}
          exit 1
      - name: Exit on bad branch
        if: ${{ !contains(fromJson(inputs.dist_branches), steps.branch.outputs.BRANCH) }}
        run: |
          echo Can't create a release on branch ${{ steps.branch.outputs.BRANCH }}
          exit 1

      - name: Prepare release tag env var
        run: |
          echo "RELEASE_VERSION=undefined" >> $GITHUB_ENV

      - name: See if major release
        if: contains(github.event.pull_request.labels.*.name, 'release:major') 
        run: |
          echo "RELEASE_VERSION=${{ steps.versions.outputs.NEW_MAJOR }}" >> $GITHUB_ENV

      - name: See if minor release
        if: contains(github.event.pull_request.labels.*.name, 'release:minor')
        run: |
          echo "RELEASE_VERSION=${{ steps.versions.outputs.NEW_MINOR }}" >> $GITHUB_ENV

      - name: See if patch release
        if: contains(github.event.pull_request.labels.*.name, 'release:patch')
        run: |
          echo "RELEASE_VERSION=${{ steps.versions.outputs.NEW_PATCH }}" >> $GITHUB_ENV

      - name: Exit if no release tag is found
        if: contains(env.RELEASE_VERSION, 'undefined')
        run: echo No release tag found - $RELEASE_VERSION

      - name: Output release version
        shell: bash
        run: echo "VERSION=$(echo $RELEASE_VERSION)" >> $GITHUB_OUTPUT
        id: version_release

      - name: Debug release version
        run: |
          echo release version ${{ steps.version_release.outputs.VERSION }}

      - uses: jungwinter/split@v2
        id: split_new
        with:
          msg: '${{ steps.version_release.outputs.VERSION }}'
          separator: '.'
          maxsplit: 3

      - name: Debug major release of new version
        run: |
          echo major release ${{ steps.split_new.outputs._0 }}

      - name: Create new version file
        if: ${{ !contains(env.RELEASE_VERSION, 'undefined') && inputs.version_ini_path != '' }}
        run: |
          echo "${{ inputs.version_ini_prefix }}$RELEASE_VERSION" > ${{ inputs.version_ini_path }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: ${{ !contains(env.RELEASE_VERSION, 'undefined') && inputs.version_ini_path != '' }}
        with:
          commit_message: "chore: update version"
          branch: ${{ steps.branch.outputs.BRANCH }}

      - name: Create release and tag
        if: ${{ !contains(env.RELEASE_VERSION, 'undefined') }}
        uses: ncipollo/release-action@v1
        with:
          name: 'Release ${{ env.RELEASE_VERSION }}'
          tag: 'v${{ env.RELEASE_VERSION }}'
          commit: ${{ steps.branch.outputs.BRANCH }}
          generateReleaseNotes: true

    outputs:
      version: ${{ steps.version_release.outputs.VERSION }}
      major: ${{ steps.split_new.outputs._0 }}
