name: 'release'

on:
  workflow_call:
    inputs:
      main_branch:
        description: Main branch, in format of a string, where a new major release is allowed
        required: true
        type: string
      dist_branches:
        required: true
        description: Branches to execute on, in format of a string JSON array
        type: string
      version_ini_path:
        required: false
        description: Path to version.ini file (optional)
        type: string
      version_ini_prefix:
        required: false
        description: Content version.ini file (optional)
        type: string

jobs:

  debug:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

  release-on-push:
    if: github.event.pull_request.merged
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Retrieve last tag on branch
        run: |
          echo "::set-output name=TAG_NAME::$(git describe --tags --abbrev=0 | cut -c 2-)"
        id: last_tag

      - name: Debug last tag
        run: |
          echo last tag ${{ steps.last_tag.outputs.TAG_NAME }}
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: '${{ steps.last_tag.outputs.TAG_NAME }}'
          separator: '.'
          maxsplit: 3

      - name: Calculate new versions
        env:
          MAJOR: ${{ steps.split.outputs._0 }}
          MINOR: ${{ steps.split.outputs._1 }}
          PATCH: ${{ steps.split.outputs._2 }}
        run: |
          echo "::set-output name=NEW_MAJOR::$(echo $((MAJOR+1)).0.0)"
          echo "::set-output name=NEW_MINOR::$(echo $MAJOR.$((MINOR+1)).0)"
          echo "::set-output name=NEW_PATCH::$(echo $MAJOR.$MINOR.$((PATCH+1)))"
        id: versions

      - name: New possible releases
        run: |
          echo new major ${{ steps.versions.outputs.NEW_MAJOR }}
          echo new minor ${{ steps.versions.outputs.NEW_MINOR }}
          echo new patch ${{ steps.versions.outputs.NEW_PATCH }}
      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=BRANCH::$(echo ${GITHUB_REF#refs/heads/})"
        id: branch

      - name: Debug branch name
        run: |
          echo current branch ${{ steps.branch.outputs.BRANCH }}
      - name: Exit on bad tag
        if: ${{ contains(github.event.pull_request.labels.*.name, 'release:major') && !contains(steps.branch.outputs.BRANCH, inputs.main_branch) }}
        run: |
          echo Can't create a major release on branch ${{ steps.branch.outputs.BRANCH }}
          exit 1
      - name: Exit on bad branch
        if: ${{ !contains(fromJson(inputs.dist_branches), steps.branch.outputs.BRANCH) }}
        run: |
          echo Can't create a release on branch ${{ steps.branch.outputs.BRANCH }}
          exit 1

      - name: Prepare release tag env var
        run: |
          echo "RELEASE_VERSION=undefined" >> $GITHUB_ENV

      - name: See if major release
        if: contains(github.event.pul_request.labels.*.name, 'release:major') 
        run: |
          echo "RELEASE_VERSION=${{ steps.versions.outputs.NEW_MAJOR }}" >> $GITHUB_ENV

      - name: See if minor release
        if: contains(github.event.pull_request.labels.*.name, 'release:minor')
        run: |
          echo "RELEASE_VERSION=${{ steps.versions.outputs.NEW_MINOR }}" >> $GITHUB_ENV

      - name: See if patch release
        if: contains(github.event.pull_request.labels.*.name, 'release:patch')
        run: |
          echo "RELEASE_VERSION=${{ steps.versions.outputs.NEW_PATCH }}" >> $GITHUB_ENV

      - name: Exit if no release tag is found
        if: contains(env.RELEASE_VERSION, 'undefined')
        run: |
          echo No release tag found - ${{ env.RELEASE_VERSION }}
          exit 0

      - name: Output release version
        shell: bash
        run: echo "::set-output name=VERSION::$(echo $RELEASE_VERSION)"
        id: version_release

      - name: Create new version file
        if: inputs.version_ini_path != ''
        run: |
          echo "${{ inputs.version_ini_prefix }}${{ env.RELEASE_VERSION }}" > ${{ inputs.version_ini_path }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        if: inputs.version_ini_path != ''
        with:
          commit_message: "chore: update version"
          branch: ${{ steps.branch.outputs.BRANCH }}

      - name: Create release and tag
        uses: ncipollo/release-action@v1
        with:
          name: 'Release ${{ env.RELEASE_VERSION }}'
          tag: 'v${{ env.RELEASE_VERSION }}'
          commit: ${{ steps.branch.outputs.BRANCH }}
          generateReleaseNotes: true

    outputs:
      version: ${{ steps.version_release.outputs.VERSION }}
